### ISSUE TITLE
the master doesn't work

### ISSUE THREAD

**Issue by kaharlin** [etweisberg/ATCompSci#40]
I got an error that says: "The view function did not return a valid response. The"

**Comment by etfriedman** [comment]
> "The view function did not return a valid response. The"

Is this the only information provided?
Was this a jinja error that displayed in your browser? Or terminal?

**Comment by kaharlin** [comment]
Dr. B found the error and Ethan fixed it so we should be good. Thanks though

**Comment by etfriedman** [comment]
ok
